//FOR ADDING ELEMENTS TO THE ORIGNAL ARRAYS
//PUSH AND UNSHIFT

//FOR REMOVE ELEMENTS TO THE ORIGNAL ARRAYS
//POP,SHIFT,SPLICE

//OTHER THAT MUTED THE ARRAYS 
//FILL,SORT,REVERSE

//WHEN WE WANT NEW ARRAY
//MAP,FILTER,SLICE,CONCNAT.FLAT,FLATMAP

//ARRAY INDEXING
//INDEXOF,FINDINDEXOF,FIND

//KNOW IF ARRAY ICNLUDES ELEMENTS
//INCLUDES,SOME,EVERY

//TRANFORM THE ARRAY IN STRING 
//REDUCE ,FOREACH