//EVENT :its as signal that generated by Node that something would be happend in browser
//example : Click Event ,Mouse Moving

//MOUSER ENTER EVENT


///////////////////////////////////////////EVENT AND EVENT LISTNERS///////////////////////////////////

//EVENT :its as signal that generated by Node that something would be happend in browser
//example : Click Event ,Mouse Moving

//MOUSER ENTER EVENT
const h1 = document.querySelector('h1');

h1.addEventListener('mouseenter', (e) => {
  alert('Great! You are reading.');
});

h1.onmouseenter = (e)=>{
  alert('deep jadav')
}